###
GET http://localhost:8082/

> {%
    client.test("Should return sample info", function() {
        client.assert(response.status === 200, "Wrong response status");
        client.assert(response.body.indexOf("Welcome to AuthorizationServer Sample with PKCE support") !== -1, 'Wrong info');
    });
 %}

###
GET http://localhost:8082/login

> {%
    client.test("Should return login page", function() {
        client.assert(response.status === 200, "Wrong response status");
        client.assert(response.body.indexOf("_csrf") !== -1, 'Wrong content');
        client.assert(response.body.indexOf("username") !== -1, 'Wrong content');
        client.assert(response.body.indexOf("password") !== -1, 'Wrong content');
    });

    client.global.set("csrf-token", response.body.match('(.*name="_csrf" type="hidden" value=")(.*)(".*)')[2] );
    client.log(client.global.get("csrf-token"))
 %}

###
POST http://localhost:8082/login
Content-Type: application/x-www-form-urlencoded

username=testuser&password=testpw&_csrf={{csrf-token}}

> {%
    client.test("Should login user", function() {
        client.assert(response.status === 302, "Wrong response status");
        client.assert(response.headers.valueOf("Location") === "http://localhost:8082/", "Wrong redirect");
    });
 %}

###
GET http://localhost:8082/home

> {%
    client.test("Should return home", function() {
        client.assert(response.status === 200, "Wrong response status");
        client.assert(response.body.indexOf("Home of user: testuser") !== -1, 'Wrong content');
    });
 %}

###
GET http://localhost:8082/oauth/authorize

> {%
    client.test("Should fail without client parameter", function() {
        client.assert(response.status === 401, "Wrong response status");
        client.assert(response.body.indexOf("Bad client credentials") !== -1, 'Wrong content');
    });
 %}