###
# @no-redirect
GET http://localhost:8081/oauth/authorize?
        response_type=code
        &client_id=private-client
        &redirect_uri=http://localhost:9091/login/oauth2/code/sample-private-client-min
        &scope=private-client-scope-min
        &state=sdf7s990s

> {%
    client.test("Should return to client with code and state", function() {
        client.assert(response.status === 302, "Wrong response status");
        client.assert(response.headers.valueOf('Location').match('(.*code=)(.*)&state=sdf7s990s') != null, "Wrong redirect");
    });

    client.global.set("authorization_code", response.headers.valueOf('Location').match('(.*code=)(.*)&state=sdf7s990s')[2] );
    client.log(client.global.get("authorization_code"))
 %}

###
POST http://localhost:8081/oauth/token?
        grant_type=authorization_code
        &code={{authorization_code}}
        &redirect_uri=http://localhost:9091/login/oauth2/code/sample-private-client-min
Authorization: Basic private-client secret

> {%
    client.test("Should return the token", function() {
        client.assert(response.status === 200, "Wrong response status");
        client.assert(response.body.access_token, "access_token is expected");
        client.assert(response.body.token_type === 'bearer', "Wrong token type");
        client.assert(response.body.refresh_token, "refresh_token is expected");
        client.assert(response.body.expires_in, "expires_in is expected");
        client.assert(response.body.scope === 'private-client-scope-min', "Wrong scope");
    });
 %}
